const ActionTypes = {
  travelHistory: {
    GET_LOCATIONS_VISITED_REQUEST: 'GET_LOCATIONS_VISITED_REQUEST',
    GET_LOCATIONS_VISITED_SUCCESS: 'GET_LOCATIONS_VISITED_SUCCESS',
    GET_LOCATIONS_VISITED_FAILURE: 'GET_LOCATIONS_VISITED_FAILURE',
  },
};

export default ActionTypes;
